const jobType = Object.freeze({
  RELAY: 'RELAY',
  POOF_WITHDRAW: 'POOF_WITHDRAW',
  MINING_REWARD: 'MINING_REWARD',
  BATCH_REWARD: 'BATCH_REWARD',
  MINING_WITHDRAW: 'MINING_WITHDRAW',
  WITHDRAW_V2: 'WITHDRAW_V2',
})

const status = Object.freeze({
  QUEUED: 'QUEUED',
  ACCEPTED: 'ACCEPTED',
  SENT: 'SENT',
  MINED: 'MINED',
  RESUBMITTED: 'RESUBMITTED',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
})

module.exports = {
  jobType,
  status,
}
